


- name: "Removal of common packages - Names: [{{ mbis_package_names }}] - Version [{{ mbis_version }}]"
  yum:
    name: "{{ mbis_package_names }}"
    state: absent
    disablerepo: "*"
    enablerepo: "{{ mbis_repository_name }}"
  become: true
  become_user: root
  async: 3600
  poll: 10
  register: _result

- ansible.builtin.debug:
    var: _result

