---
- hosts: all
  become: yes
  gather_facts: yes
  remote_user: svc_ansible
  vars_files:
    - ~/svc_ansible.yml

  tasks:
  - name: collect facts about the system services
    ansible.builtin.systemd:
      name: firewalld
    register: firewall_status

  - name: Debug
    debug:
      msg: Server {{ inventory_hostname }} - firewall is {{ firewall_status.status.ActiveState }} and {{ firewall_status.status.UnitFileState }}
