---
# tasks file for mbis-testdata-insert


  - name: "Deploy test data on host"
    ansible.builtin.shell: |
      chmod +x ttt_insert_testdata.sh
      ./ttt_insert_testdata.sh -U system -P Printrak
    args:
      chdir: /home/bisora/scripts/schema/ttt/
    become: true
    become_user: bisora  #will change in prod, create a var !
    become_method: sudo   # Become method being used when manually running scripts
    become_flags: '-i'  # adding -l to load the user profile which includes environment variables.
    register: _result

  - name: Print return information from the previous task
    ansible.builtin.debug:
      var: _result.stdout_lines
