---

- name: Start Tera, monitor logs for " ERROR " for 10 seconds
  ansible.builtin.command: /opt/bis/scripts/TeraStartup && timeout 10 tail -f /opt/bis/log/tera.log
  become_user: bis
  become: true
  become_method: sudo   # Become method being used when manually running scripts
  become_flags: '-i'  # adding -l to load th user profile which includes environment variables.
  register: result
  failed_when: "'Running with PID' not in result.stdout or ' ERROR ' in result.stdout"
