---

- name: Shutdown MBIS
  hosts: mbis_jboss, mbis_des, mbis_fes, mbis_SSO, mbis_tera
  remote_user: root
  become: true
  become_user: bis
  become_method: sudo   # Become method being used when manually running scripts
  become_flags: '-i'  # adding -l to load the user profile which includes environment variables.

  pre_tasks:

  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Populate service facts
    ansible.builtin.service_facts:

  - name: Send shutdown mbis notificaiton
    ansible.builtin.command: echo "notify shutdown"
    notify: "shutdown mbis"

  tasks:

  - ansible.builtin.import_role:
      name: mbis/mbis-tera-install
      tasks_from: empty.yml
  - ansible.builtin.import_role:
      name: mbis/mbis-sso-install
      tasks_from: empty.yml
  - ansible.builtin.import_role:
      name: mbis/mbis-wms
      tasks_from: empty.yml
  - ansible.builtin.import_role:
      name: mbis/mbis-wfs
      tasks_from: empty.yml
  - ansible.builtin.import_role:
      name: mbis/mbis-app-install
      tasks_from: empty.yml
  - ansible.builtin.import_role:
      name: mbis/mbis-des-install
      tasks_from: empty.yml
  - ansible.builtin.import_role:
      name: mbis/mbis-fes-install
      tasks_from: empty.yml
  - ansible.builtin.import_role:
      name: mbis/mbis-tera-install
      tasks_from: empty.yml

