######################
##
## Configure Oracle servers
## ansible-playbook -l SERVER, site.yml --tags=users
##
##############################

---
- hosts: all
  become: yes
  gather_facts: true

  roles:
    - role: cleanup             # remove any existing oracle groups and users
      tags: cleanup
    - role: users               # create users and groups
      tags: users
    - role: folders             # create folders        
      tags: folders
    - role: packages            # install required packages
      tags: packages
    - role: other               # other stuff requested by the French team
      tags: other
    - role: ownership           # set/fix ownership
      tags: ownership
