---

# tasks file for mbis-elk_custo

- name: "TEST: Yum Install MBIS elk custo packages "
  yum:
    name: "{{ custorepopackagepath }}bis-customization-elk-mbis.rpm"
    state: present
    disablerepo: "*"
  become: true
  become_user: root
  register: _yumcustoinstall
  check_mode: yes

- name: Uninstall Elk Custo package when yum detects a file conflict
  import_tasks: uninstall.yml
  when: _yumcustoinstall.changed or _yumcustoinstall.failed

# TBC
# - name: Uninstall des custo package when yum detects a file conflict
#   ansible.builtin.import_role:
#     name: mbis/mbis-des_custo_mig-install
#     tasks_from: uninstall.yml
#   when: _yumcustoinstall.changed or _yumcustoinstall.failed

- name: "Install MBIS des custo packages "
  ansible.builtin.shell: |
    rpm -ivh --replacefiles {{custorepopackagepath}}bis-customization-elk-mbis.rpm
  become: true
  become_user: root
  register: result
  #notify: "postinstall mbis"
  when: _yumcustoinstall.changed or _yumcustoinstall.failed

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result.stdout_lines
  when: _yumcustoinstall.changed or _yumcustoinstall.failed



