---
# handlers file for mbis-app-install

- name: Mbis shutdown commands
  include_tasks: handlers/shutdown.yml
  listen: "shutdown mbis"

- name: Mbis Post Install commands
  include_tasks: handlers/postinstall.yml
  listen: "postinstall mbis"

- name: Mbis PreStartup commands
  include_tasks: handlers/prestartup.yml
  listen: "prestartup mbis"

- name: Mbis Startup commands
  include_tasks: handlers/startup.yml
  listen: "startup mbis"

