---





- name: Start AppServer
  ansible.builtin.command: /opt/bis/scripts/AppServerStartup
  become_user: bis
  become: true
  become_method: sudo   # Become method being used when manually running scripts
  become_flags: '-i'  # adding -l to load the user profile which includes environment variables.
  register: _results
  failed_when: "'starting with PID' not in _results.stdout"

- name: Wait 90 seconds for AppServer port 9993 to become open on the host, don't start checking for 5 seconds
  wait_for:
    port: 9993
    delay: 5
    timeout: 90


- name: DsmStartup
  ansible.builtin.command: /opt/bis/scripts/DsmStartup
  become_user: bis
  become: true
  become_method: sudo   # Become method being used when manually running scripts
  become_flags: '-i'  # adding -l to load the user profile which includes environment variables.
  register: result
