---
- name: Mount /opt/bis
  ansible.posix.mount:
    src: /dev/mapper/rootvg-optbislv 
    path: /opt/bis 
    fstype: ext4 
    opts: defaults
    state: mounted

- name: Make the log folder
  ansible.builtin.file:
    path: /opt/bis/log
    state: directory
    mode: '0755'

- name: Mount /opt/bis/log
  ansible.posix.mount:
    src: /dev/mapper/rootvg-optbisloglv
    path:  /opt/bis/log 
    fstype: ext4 
    opts: defaults
    state: mounted
