---
- hosts: test 
    - name: Creating user "{{ uusername }}" with admin access
        vars:
          uusername:
            - ansadmin
        user:
          name: {{ uusername }}
          password: {{ upassword | password_hash('sha512') }}
          groups: admin append=yes
          when:  assigned_role  == "yes"
