---
# tasks file for mbis-des_custo-install


- name: "TEST: Yum Install MBIS Des custo packages "
  yum:
    name: "{{custorepopackagepath}}bis-customization-des-mbis.rpm"
    state: present
    disablerepo: "*"
  become: true
  become_user: root
  register: _yumcustoinstall
  check_mode: yes

- name: Uninstall Des custo package when yum detects a file conflict
  import_tasks: uninstall.yml
  when: _yumcustoinstall.changed or _yumcustoinstall.failed

- name: "Install MBIS des custo packages "
  ansible.builtin.shell: |
    rpm -ivh --replacefiles {{custorepopackagepath}}bis-customization-des-mbis.rpm
  become: true
  become_user: root
  register: result
  #notify: "postinstall mbis"
  when: _yumcustoinstall.changed or _yumcustoinstall.failed

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result.stdout_lines
  when: _yumcustoinstall.changed or _yumcustoinstall.failed

- name: TEMP - remove /opt/bis/des/fastID, remove once we have deplyed to prototype (last week of july)
  ansible.builtin.file:
    path: /opt/bis/des/fastID
    state: absent
  become: true
  become_user: root
