- name: update any packages that are required to install the security patches
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - sssd
    - json-c
    - dhcp-client 
