# add svc_tenable account to sudoers file
---
- hosts: all
  become: yes
  remote_user: svc_ansible
  vars_files:
    - ~/svc_ansible.yml

  tasks:
  - name: Add user to AllowGroups
    replace:
      backup: yes
      dest: /etc/ssh/sshd_config
      regexp: '^(AllowGroups(?!.*\b svc_tenablesc \b).*)$'
      replace: '\1 svc_tenablesc'
  - name: Add line to sudoers file
    lineinfile:
      path: /etc/sudoers
      line: svc_tenable ALL=(root) ALL
  - name: Restart SSH
    service:
      name: sshd
      state: restarted
