---


- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto


- name: "remove custo packages: {{ mbis_package_name }}"
  ansible.builtin.shell: "rpm --erase --justdb --allmatches -v {{ mbis_package_name }}"
  ignore_errors: yes
  become: true
  become_user: root
  register: _result
  when: "mbis_package_name in ansible_facts.packages"
  changed_when: "'Preparing packages...' in _result.stdout"



- ansible.builtin.debug:
    var: _result.stdout_lines