- name: Check if restart is required
  shell: needs-restarting -r
  register: result
  failed_when: false
  changed_when: result.rc == 0

- name: Reboot server and wait up to 5 minute for it to return
  when: result.rc == 1
  reboot:
    reboot_timeout: 300
