---
# tasks file for mbis-tera-install


- name: Install tera packages
  tags: install
  block:
  - name: "Installation of MBIS tera STD packages - Names: [{{ mbis_package_names }}] - Version [{{ mbis_version }}]"
    yum:
      name: "{{ mbis_package_names }}"
      state: latest
      disablerepo: "*"
      enablerepo: "{{ mbis_repository_name }}"
    become: true
    become_user: root
    async: 3600
    poll: 10
    register: _result
    notify: "postinstall mbis"

  - ansible.builtin.debug:
      var: _result