---
- hosts: FES,DES,JBOSS
  become: yes

  tasks:
  - name: Start FES
    become_user: bis
    ansible.builtin.command: /opt/bis/scripts/FesStartup

  - name: Start FESMig
    become_user: bis
    ansible.builtin.command: /opt/bis/scripts/FesMigStartup
    delegate_to: SERVER07

