---
# tasks file for mbis-wfs

- name: Install WFS packages
  block:
  - name: "Installation of MBIS WFS STD packages - Names: [{{ mbis_package_names }}] - Version [{{ mbis_version }}]"
    yum:
      name: "{{ mbis_package_names }}"
      state: latest
      enablerepo: "{{ mbis_repository_name }}"
    become: true
    become_user: root
    async: 3600
    poll: 10
    register: _result
    notify: "postinstall mbis"

- debug :
    var: _result