---
# tasks file for mbis-etchosts

- name: Populate host file
  block:
  - name: Remove name entries in the hosts file
    ansible.builtin.replace:
      path: "{{ hostfile }}"
      replace: ''
      regexp: '\b{{ item }}(?!\.)'
    become: true
    become_user: root
    with_items: "{{ hostnames }}"


  - name: Make sure there is no empty IP address in the host file
    ansible.builtin.lineinfile:
      path: "{{ hostfile }}"
      state: absent
      regexp: '^\d*\.*\d*\.\d*\.\d*\s*$'
    become: true
    become_user: root

  - name: Add name entries in the hosts file
    ansible.builtin.lineinfile:
      path: "{{ hostfile }}"
      state: present
      line: "{{ IPaddress }} {{ hostnames | join(' ') }}"
      create: yes
    become: true
    become_user: root