---

- name: Remove name entries in the hosts file
  ansible.builtin.replace:
    path: /etc/hosts
    replace: ''
    regexp: '\b{{ item }}(?!\.)'
  become: true
  become_user: root
  with_items:
    - keycloak
    - keycloak.mbis-dev.idemia.com
    - bismatcher
    - bisdb
    - bisapp
    - bisapp.mbis-dev.idemia.com
    - ptkads
    - bisartemis
    - bisartemis.mbis-dev.idemia.com
    - mbss

- name: Make sure there is no empty IP address in the host file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: absent
    regexp: '^\d*\.*\d*\.\d*\.\d*\s*$'
  become: true
  become_user: root

