---
- name: Collect Logs
  gather_facts: yes
  become: yes
  hosts: FES

  tasks:
    - name: Collect fes.log from all machines
      ansible.builtin.fetch:
        src: /opt/bis/log/fes.log
        dest: /tmp/logs/
