- name: Create the directory if it does not exist
  ansible.builtin.file:
    path: "{{ local_path }}"
    state: directory
    mode: '0755'
    
- name: Add entry to fstab file
  blockinfile:
    path: /etc/fstab
    block: |
      "/dev/mapper/{{ volume_group }}-{{ logical_volume }} {{ local_path }} {{ filesystem_type }} 1 2"

# - name: Mount file system
#   mount:
#     src: "/dev/mapper/{{ volume_group }}-{{ logical_volume }}"
#     path: "{{ local_path }}" 
#     fstype: "{{ filesystem_type }}"
#     state: mounted
