---
# tasks file for mbis-oracle_custo-install

- name: "TEST: Yum Install MBIS Oracle custo packages "
  yum:
    name: "{{custorepopackagepath}}bis-customization-dbm-oracle-mbis.rpm"
    state: present
    disablerepo: "*"
  ignore_errors: yes
  become: true
  become_user: root
  register: _yumcustoinstall
  check_mode: yes

- name: Uninstall Oracle Custo package when yum detects a file conflict
  import_tasks: uninstall.yml
  when: _yumcustoinstall.changed or _yumcustoinstall.failed


- name: "Install MBIS dbm custo packages"
  ansible.builtin.shell: |
    rpm -ivh --replacefiles {{custorepopackagepath}}bis-customization-dbm-oracle-mbis.rpm
  become: true
  become_user: root
  register: _result
  notify: "postinstall mbis"
  when: _yumcustoinstall.changed or _yumcustoinstall.failed


- name: Print return information from the previous task
  ansible.builtin.debug:
    var: _result.stdout_lines
  when: _yumcustoinstall.changed or _yumcustoinstall.failed
