---


- name: Start WMS
  ansible.builtin.command: /opt/bis/scripts/WmsStartup
  become_user: bis
  become: true
  become_method: sudo   # Become method being used when manually running scripts
  become_flags: '-i'  # adding -l to load the user profile which includes environment variables.
  register: result
  failed_when: "'Running with PID' not in result.stdout"

- name: Wait 120 seconds for Wms Https Server to start on port 61616 to become open on the host, don't start checking for 5 seconds
  wait_for:
    port: 61616
    delay: 5
    timeout: 120