- name: Make sure node_exporter user exists
  user:
    name: node_exporter
    state: present
    createhome: no
    shell: /usr/bin/false

- name: Copy executable file to the server and set owner and permission
  copy:
    src: node_exporter
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '0755'

- name: Copy the service file and set owner and permission
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'

- name: Start service 
  service:
    name: node_exporter.service
    state: started
    enabled: yes

- name: make text file upload folder
  ansible.builtin.file:
    path: /tmp/node
    owner: root
    group: root
    mode: '755'
    
    # - name: open firewall ports
    #   ansible.posix.firewalld:
    #     port: 9100/tcp
    #     permanent: yes
    #     state: enabled
    #     immediate: yes

